# This workflow builds the MAUI app for Windows on every commit to the main branch
name: Build MAUI Windows

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x"

      - name: Restore dependencies
        run: dotnet restore BedrockAddonTidy/BedrockAddonTidy.csproj

      - name: Build MAUI Windows
        run: dotnet build BedrockAddonTidy/BedrockAddonTidy.csproj -c Release -f:net9.0-windows10.0.17763.0

      - name: Publish MAUI Windows
        run: dotnet publish BedrockAddonTidy/BedrockAddonTidy.csproj -c Release -f:net9.0-windows10.0.17763.0 -o publish
