# This workflow builds and uploads a release asset for Windows when a GitHub Release is created
name: Release MAUI Windows

on:
  release:
    types: [published]

jobs:
  build-and-release-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x"

      - name: Restore dependencies
        run: dotnet restore BedrockAddonTidy/BedrockAddonTidy.csproj

      - name: Build MAUI Windows
        run: dotnet build BedrockAddonTidy/BedrockAddonTidy.csproj -c Release -f:net9.0-windows10.0.19041.0

      - name: Publish MAUI Windows
        run: dotnet publish BedrockAddonTidy/BedrockAddonTidy.csproj -c Release -f:net9.0-windows10.0.19041.0 -o publish

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: publish/**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
